### ISSUE TITLE
Tx never goes through

### ISSUE THREAD

**Issue by bytes0xcr6** [StardustCollective/dag4.js#19]
Hi! 

When trying to send a single Tx or batch Tx to the integrationnet 2.0, I get a tx hash in return but the tx is never pushed to the chain.

Tx hash: [9ff4ced96314104929fb8051a377502dc30e53cbe892022cdc42410976cfebfb](https://integrationnet.dagexplorer.io/transactions/9ff4ced96314104929fb8051a377502dc30e53cbe892022cdc42410976cfebfb
)

I have been following the documentations and this code used to work before. Could you help here? Please

- Package: ` "@stardust-collective/dag4": "^2.2.0"`

Chain configuration: 
```Typescript
  dag4.account.connect({
    networkVersion: "2.0",
    beUrl: "https://be-integrationnet.constellationnetwork.io",
    l0Url: "https://l0-lb-integrationnet.constellationnetwork.io",
    l1Url: "https://l1-lb-integrationnet.constellationnetwork.io",
  });
```

Script:
```Typescript
async function simpleTransfer(to: string, amount: number) {
  const address = dag4.account.address;

  console.log("sending from :", address);

  const res = await dag4.account.transferDag(
    to,
    amount, 
    0 
  );

  console.log(res);
}

simpleTransfer("DAG7sx7SSuGNeM88qm4hdpoCnveQE9QCraf4Mj3C", 10);
```

**Comment by AlexBrandes** [comment]
This is likely an issue with the specific node that you've connected to through the load balancer API. Are you able to successfully send transactions if you connect to an individual node directly via IP address?

**Comment by bytes0xcr6** [comment]
Still getting the same problem, even if I connect to an individual node directly via IP address...

**Comment by bytes0xcr6** [comment]
Solved, it was due to some inestability in the network L1, but it´s solved now!

**Comment by bytes0xcr6** [comment]
Solved, it was due to some inestability in the network L1, but it´s solved now!
