### ISSUE TITLE
Transaction hash offline

### ISSUE THREAD

**Issue by anhcao142** [StardustCollective/dag4.js#2]
Hi, is it possible to generate transaction hash before posting it to the network? Not DAG but when working with other blockchains, I sometimes encounter network error when submitting transactions. When that happens, I couldn't track if the transaction was included in the block without the offline txHash.

**Comment by ffox77** [comment]
https://github.com/StardustCollective/dag4.js/wiki/Exchange-Integration#sign-transactions-online-or-offline
