### ISSUE TITLE
Errors when checking balance for DAG Public Key

### ISSUE THREAD

**Issue by bytes0xcr6** [StardustCollective/dag4.js#21]
**Description:**

I encounter errors when attempting to check the balance of any DAG Public Key. The errors vary, and I sometimes receive **Error 1** and other times **Error 2**:

- **Error 1:**  
  `Error: Error`

- **Error 2:**  
  ```
  Error: 503 Service Temporarily Unavailable
  ```

**Steps to Reproduce:**

```typescript
import { dag4 } from "@stardust-collective/dag4";


  dag4.account.connect({
    networkVersion: "2.0",
    testnet: false, // False or True for mainnet/testnet
  });

const { balance } = await dag4.network.getAddressBalance(dagAddress);
```

**Version:**  
`"@stardust-collective/dag4": "2.2.2"`

**Request for Assistance:**  
Could you please help me resolve this issue?

**Comment by AlexBrandes** [comment]
The 503 error comes from the network load balancers. There were some issues with the load balancers last night but they were resolved fairly quickly. You can try to connect again. 

Either way, this isn't an issue w/dag4 so I'll close the ticket here.
